[environments.production.build]
builder = "NIXPACKS"
buildCommand = "true"

# this needs to reset the database and then seed it? is that just a seed?
[environments.pr.build]
builder = "NIXPACKS"
buildCommand = "npm run seed"

[environments.production.deploy]
startCommand = "true"
restartPolicyType = "NEVER"
 

#figure out how to set VERCEL_TOKEN in here

[environments.pr.deploy]
#startCommand = "vercel help"
startCommand = "vercel -y -e DATABASE_URL=$DATABASE_URL --token=w7rfpEBCAPb3BlJEK0JON1RY"
#startCommand = "export"
restartPolicyType = "NEVER"
