[environments.production.build]
builder = "NIXPACKS"
buildCommand = "true"

# this needs to reset the database and then seed it? is that just a seed?
[environments.pr.build]
builder = "NIXPACKS"
buildCommand = "npm run seed"

[deploy]
startCommand = "true"
restartPolicyType = "NEVER"