[environments.production.build]
builder = "NIXPACKS"
buildCommand = "true"

[environments.pr.build]
builder = "NIXPACKS"
buildCommand = "true"

[deploy]
startCommand = "true"
restartPolicyType = "NEVER"