import { type NextPage } from "next";
import Head from "next/head";
import type { CSSProperties } from "react";
import RingLoader from "react-spinners/RingLoader";
import Penta from "../components/Penta";

import { trpc } from "../../utils/trpc";

const override: CSSProperties = {
  display: "block",
  margin: "0 auto",
  borderColor: "red",
};

const Pentas: NextPage = () => {
  
  const { data: pentas } = trpc.penta.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Katamino</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-10 mt-10">
          <div className="col-start-2 col-end-10">
            <h1 className="text-center text-2xl font-extrabold leading-normal text-gray-700 md:text-[4rem]">
              Pick a <span className="text-purple-300">P</span>enta to Play
            </h1>
          </div>
          <div className="col-start-2 col-end-10 mt-10">
            {pentas ? 
              <table className="table table-zebra w-full">
                <thead>
                  <tr>
                    <th>️Play</th>
                    <th>ID</th>
                    <th>Columns</th>
                    <th>Penta</th>
                  </tr>
                </thead>
                <tbody>
                  {pentas && pentas.map((penta) => (
                    <tr key={penta.id} className="hover">
                      <td>
                        <a href={'pentas/' + penta.id} role="button" className="btn btn-primary btn-circle">🕹️</a>
                      </td>
                      <td>{penta.id}</td>
                      <td>{penta.columns}</td>
                      <td>
                        <Penta penta={penta} size={15}></Penta>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
              : <div className="mt-20">
                  <RingLoader
                    color={"hsl(var(--pf))"}
                    cssOverride={override}
                    size={75}
                    aria-label="Loading Spinner"
                    data-testid="loader"
                  />
                </div>
            }
          </div>
        </div>
      </main>
    </>
  )
}

export default Pentas