import { type NextPage } from "next";
import { useRouter } from 'next/router'
import { type InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { signIn, getProviders, useSession } from 'next-auth/react'
import { useEffect } from "react";
import { router } from "../../server/trpc/trpc";

const Login: NextPage = (props: any) => {

  const { data: sessionData } = useSession();
  
  const nextRouter = useRouter();
  useEffect(() => {
    if (sessionData) {
      nextRouter.push('/pentas')
    }
  }, [nextRouter, sessionData])

  // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain
  const github = props.providers?.github!
  // eslint-disable-next-line @typescript-eslint/no-non-null-asserted-optional-chain
  const auth0 = props.providers?.auth0!

  return (
    <>
      <Head>
        <title>Katamino</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center p-4">

        <div className="grid grid-cols-2 gap-10 mb-2">
          <button onClick={() => signIn(auth0.id)} className="btn btn-primary btn-lg drop-shadow-lg">
            Auth0
          </button>
          <button onClick={() => signIn(github.id)} className="btn btn-primary btn-lg drop-shadow-lg">
            GitHub
          </button>
        </div>

        <h1 className="ml-[175px] text-[5rem] leading-normal text-gray-600">
          <span className="text-primary font-extrabold">L</span>ogin
        </h1>

        <div className="relative top-[-140px] left-[30px] text-primary text-[250px] rotate-90">
          )
        </div>

      </main>
    </>
  );
};

export default Login;

export async function getServerSideProps() {
  const providers = await getProviders()
  return {
    props: { providers },
  }
}