import { type NextPage } from "next";
import Head from "next/head";
import Square from "./components/Square";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {


  return (
    <>
      <Head>
        <title>Katamino</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Play <span className="text-purple-300">K</span>atamino
        </h1>
        <div className="grid grid-cols-7 gap-0">
          <Square color="#ffaaaa"></Square>
          <Square color="#aaaaaa"></Square>
          <Square color="#aaaaaa"></Square>
          <Square color="#aaaaaa"></Square>
          <Square color="#aaaaaa"></Square>
          <Square color="#aaaaaa"></Square>
          <Square color="#aaaaaa"></Square>
        </div>
        <AuthShowcase />
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {sessionData && (
        <p className="text-blue-500">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
      <button
        className="rounded-md border border-black bg-violet-50 px-4 py-2 text-xl shadow-lg hover:bg-violet-100"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
