import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Play <span className="text-purple-300">Katamino</span>
        </h1>
        <p className="text-2xl text-gray-700">Explore this app:</p>
        <div className="mt-3 grid gap-3 pt-3 text-center md:grid-cols-3 lg:w-2/3">
          <Card
            name="Pieces"
            description="Edit and create pieces available"
            link="piece"
          />
          <Card
            name="Pentas"
            description="Pick or create challenges made of pieces"
            link="penta"
          />
        </div>
      </main>

    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  link: string;
};

const Card = ({
  name,
  description,
  link,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
       <a
        className="m-auto mt-2 w-fit text-md text-violet-500 underline decoration-dotted underline-offset-2"
        href={link}
        rel="noreferrer"
      >
        {name}
      </a>
      <p className="text-sm text-gray-600">{description}</p>
    </section>
  );
};
