name: Build PR Preview Deployment

env:
  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID}}
  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_ID}}
  AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER}}
  DATABASE_URL: ${{ secrets.DATABASE_URL}}
  GITHUB_ID: ${{ secrets.GH_ID}}
  GITHUB_SECRET: ${{ secrets.GH_SECRET}}
  #NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL}}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}

on: [pull_request]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         mkdir .vercel
         mkdir .railway
      - name: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'project.json'
          json: ${{ secrets.VERCEL_CONFIG }}
          dir: '.vercel/'
      - name: create-json
        uses: jsdaniell/create-json@v1.2.1
        with:
          name: 'config.json'
          json: ${{ secrets.RAILWAY_CONFIG }}
          dir: '.railway/'
      - run: |
         npm install
         npx railway whoami
         vercel --token=${{ secrets.VERCEL_TOKEN }}
      #- uses: amondnet/vercel-action@v20 #deploy
        #with:
          #vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          #github-token: ${{ secrets.GH_PAT }} #Optional 
          ## vercel-args: '--prod' #Optional
          #vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          #vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 