on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: minor
          use_github_release_notes: true