on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.27.0
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version
        run: npm version ${{ steps.release.outputs.version }}

      - name: Verified commit
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        with:
          files: |
            package.json
          commit-message: 🪄 Updating version
          ref: refs/heads/main
